### ISSUE TITLE
Click on page routes back to root path

### ISSUE THREAD

**Issue by Corkle** [venantius/accountant#20]
Secretary's root path function is getting executed whenever I click anywhere on the current page. This only appears to happen when have a catch-all route defined.

This was also a symptom in issue https://github.com/venantius/accountant/issues/5 but a resolution was not reported. I am also unable to navigate routes by typing the URL in the address bar.

I've slimmed down the code to where the issue is reproducible on multiple machines:

```
(ns acc-test.core
  (:require
    [secretary.core :as secretary :refer-macros [defroute]]
    [accountant.core :as accountant]
    ))

(accountant/configure-navigation!)

(defroute home-path "/" []
  (js/console.log "Home!")
  )

(defroute about-path "/about" []
  (aset (.getElementById js/document "root") "innerHTML" "<h1>ABOUT</h1><a href='/'>home</a>"))

(defroute "*" []
  (js/console.log "Route not found."))
```

Is there additional configuration in Secretary or Accountant that I am missing?

**Comment by venantius** [comment]
Hmm, interesting. I can replicate your behavior, and it is definitely tied to the catch-all route. Using your example I can't get navigation either (even if I remove the catch-all). Clearly I haven't been active in this project for some time.

**Comment by venantius** [comment]
I think the navigation issue is related to the naive behavior of the default figwheel server and is actually unrelated to accountant. If, for instance, you copy your `resources/public/index.html` to `resources/public/about`, then you'll have navigation and on-load. 

This does, however, leave in place the issue you've identified, wherein the catchall route triggers the behavior of the home-path route dispatcher. I wonder if this, too, is related to the naive behavior of the default figwheel server. I don't define these sort of catchall-routes on the frontend, personally - I'd rather have them defined on the backend. I'd be curious what happens if you dig further on this issue.

**Comment by venantius** [comment]
I wanted to check back in on this - I'm not sure if this is still an issue these days or not, but I'm trying to do a bit of issue cleanup and this is pretty stale. I'm going to close it for now - if people are still experiencing this I'll re-open.
